### ISSUE TITLE
Fatal error: Cannot redeclare tgmpa_load_bulk_installer() 

### ISSUE THREAD

**Issue by tomaszszczerba** [michakpl/woocommerce-gateway-dotpay#2]
Witam,

Kiedy próbuję włączyć Państwa wtyczke dostaję bład jak w nagłówku w moim theme:
/shop/wp-content/themes/bearded-master/inc/class-tgm-plugin-activation.php on line 1692

Czy wiedzą państwo co może być przyczyną?

pozdrawiam,
Tomek.

**Comment by michakpl** [comment]
Problem leży po stronie thema, który ma niezaktualizowaną bibliotekę TGM Plugin Activation. Wystarczy zakomentować poniższą linijkę w pliku woocommerce-gateway-dotpay.php

require_once dirname(__FILE__) . '/includes/required_plugins.php';

Lub skopiować plik class-tgm-plugin-activation.php z folderu includes i zastąpić go plikiem o takiej samej nazwie w katalogu theme.
