### ISSUE TITLE
Cancelled order

### ISSUE THREAD

**Issue by tomaszszczerba** [michakpl/woocommerce-gateway-dotpay#4]
Witam,

Każda płatność przyjęta przez bramkę dotpay kończy się jako anulowana. Czy powinieniem (i jak) ustawić adres urlc ?

Pozdrawiam,
Tomek.

**Comment by michakpl** [comment]
Sprawdź czy w panelu Dotpay pod linkiem parametry URLC masz zaznaczone Zezwól na przyjęcie parametru URLC z zewnętrznego serwisu. Dodatkowo podaj jeszcze w panelu Dotpay i w panelu wtyczki unikalny PIN, mogą to być losowe znaki, minimum 16, w Dotpay podajesz go na tej samej stronie.

Jeśli to nie zadziałą to spróbuj z testowymi danymi i daj znać, wtedy będziemy wiedzieć po której stronie jest błąd:
ID: 249938
PIN: tFwk9wDt3YBSEzEckifqypGb2KUcmsrA

**Comment by tomaszszczerba** [comment]
Odznaczyłem "Blokuj zewnętrzne urlc" chyba logika się zmieniła. Dzięki!
