### ISSUE TITLE
changing status from completed to pending

### ISSUE THREAD

**Issue by crazyluki** [michakpl/woocommerce-gateway-dotpay#5]
Hi,
recently i discovered, that your plugin - randomly (i cannot find a rule) is changing status of orders. After marking up orders as completed - plugin changing status to pending.

**Comment by michakpl** [comment]
Hi,
Can you tell me how long after changing status of order to completed it's automatically changing it to pending?

This plugin is used by many shops, but there wasn't any similar issues earlier. I also tested it now with few orders, but I can't repeat this error at my WP installation.

**Comment by crazyluki** [comment]
Hi,
I can't tell you for sure. It's always shift overnight.
CHK Blockade is checked.
It is possible that is switching for over 1 hour. I have enabled options to
manage stock. It moves unpaid orders 1 hour after unpaid transactions.



2015-09-16 17:46 GMT+02:00 Michał Groele <notifications@github.com>:

> Hi,
> Can you tell me how long after changing status of order to completed it's
> automatically changing it to pending?
>
> This plugin is used by many shops, but there wasn't any similar issues
> earlier. I also tested it now with few orders, but I can't repeat this
> error at my WP installation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michakpl/woocommerce-gateway-dotpay/issues/5#issuecomment-140782659>
> .
>



-- 
Życzę miłego dnia
Best Regards

Łukasz Bielawski

**Comment by michakpl** [comment]
Can you send me the list of plugins you using in your WordPress installation?
