### ISSUE TITLE
Brak opisów w WooCommerce 2.6

### ISSUE THREAD

**Issue by SukcesStrony** [michakpl/woocommerce-gateway-dotpay#6]
W WooCommerce 2.6 opis metody płatności wyświetlany na stronie realizacji płatności (checkout) brzmi "Płatność poprzez Dotpay" niezależnie od ustawień tego tekstu w panelu administracyjnym.

**Comment by michakpl** [comment]
Hi,

This projects is no longer maintained in this version. Please use [official Dotpay WooCommerce plugin] (https://github.com/dotpay/WooCommerce2/releases/tag/v3.0.3)
